pyrpl: # General configuration of the software:
  name: test_refactor2
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAeAAAAESPwBAAAAAfwAAAAAAAAHgAAAA0MA////+gAAAAEBAAAA
    CPsAAAAIAGEAcwBnAHMAAAAAAP////8AAAAWAP////sAAAAGAGkAcQBzAQAAAAD/////AAADQwD/
    ///7AAAACABwAGkAZABzAAAAAAD/////AAAAFgD////7AAAADABzAGMAbwBwAGUAcwAAAAAA////
    /wAABBEA////+wAAAAgAaQBpAHIAcwAAAAAA/////wAAABYA////+wAAAAQAbgBhAAAAAAD/////
    AAAAFgD////7AAAAIgBzAHAAZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIAAAAAAP////8A
    AANkAP////sAAAAOAGwAbwBjAGsAYgBvAHgAAAAAAP////8AAAKEAP///wAAB4AAAAAAAAAABAAA
    AAQAAAAIAAAACPwAAAAA
  window_position:
  - -8
  - -8
  - 1920
  - 1137
redpitaya:
  hostname: 10.214.1.28
  user: root
  password: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas: !!omap
- na: !!omap []
spectrum_analyzers: !!omap
- spectrum_analyzer: !!omap [{center: 0}]
lockboxs: !!omap
- lockbox: !!omap
  - fabryperots: !!omap
    - FabryPerot: !!omap []
  - transmissions: !!omap
    - transmission: !!omap []
  - reflections: !!omap
    - reflection: !!omap []
  - pdhs: !!omap
    - pdh: !!omap []
  - sequences: !!omap
    - sequence: !!omap []
hks: !!omap
- hk: !!omap []
amss: !!omap
- ams: !!omap []
scopes: !!omap
- scope: !!omap [{trigger_source: immediately}, {running_continuous: true}, {duration: 8.589934592},
    {rolling_mode: true}]
samplers: !!omap
- sampler: !!omap []
asgs: !!omap
- asg1: !!omap []
- asg2: !!omap []
pwms: !!omap
- pwm1: !!omap []
- pwm2: !!omap []
pids: !!omap
- pid1: !!omap []
- pid2: !!omap []
- pid3: !!omap []
- pid4: !!omap []
iirs: !!omap
- iir: !!omap []
iqs: !!omap
- iq2: !!omap
  - frequency: 0
