pyrpl:
  name: test_refactor
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAAAAAAAAPwBAAAAAfwAAAAA/////wAAAAAA////+v////8BAAAA
    CPsAAAAIAGEAcwBnAHMAAAAAAP////8AAAAUAP////sAAAAGAGkAcQBzAAAAAAD/////AAAAFAD/
    ///7AAAACABwAGkAZABzAAAAAAD/////AAAAFAD////7AAAADABzAGMAbwBwAGUAcwAAAAAA////
    /wAAABQA////+wAAAAgAaQBpAHIAcwAAAAAA/////wAAABQA////+wAAAAQAbgBhAAAAAAD/////
    AAAAFAD////7AAAAIgBzAHAAZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIAAAAAAP////8A
    AAAUAP////sAAAAOAGwAbwBjAGsAYgBvAHgAAAAAAP////8AAAAUAP///wAAAAAAAAAAAAAABAAA
    AAQAAAAIAAAACPwAAAAA
  window_position:
  - 0
  - 0
  - 800
  - 600
redpitaya:
  hostname: 192.168.1.107
  user: root
  password: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer: {}
lockboxs:
  lockbox:
    fabryperots:
      FabryPerot: {}
    transmissions:
      transmission: {}
    reflections:
      reflection: {}
    pdhs:
      pdh: {}
    sequences:
      sequence: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {}
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir: {}
