
dependencies:
  build:
    - python:2.7
    - anaconda2:latest

build_targets:
  - name: default
    commands:
      - conda create -q -n test-environment numpy scipy paramiko pandas nose pip pyqt qtpy
      - python setup.py install
