pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAWOAAADEfwBAAAAAfwAAAAAAAAFjgAABOgA////+gAAAAcBAAAA
    CPsAAAAMAHMAYwBvAHAAZQBzAQAAAAD/////AAAEBQD////7AAAACABwAGkAZABzAQAAAAD/////
    AAACQwD////7AAAACABhAHMAZwBzAQAAAAD/////AAACJQD////7AAAABgBpAHEAcwEAAAAA////
    /wAAAzcA////+wAAAAgAaQBpAHIAcwAAAAAA/////wAAABYA////+wAAAAQAbgBhAQAAAAD/////
    AAAD1AD////7AAAAIgBzAHAAZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8A
    AANUAP////sAAAAOAGwAbwBjAGsAYgBvAHgBAAAAAP////8AAAToAP///wAABY4AAAAAAAAABAAA
    AAQAAAAIAAAACPwAAAAA
  window_position:
  - 1
  - 0
  - 1422
  - 826
redpitaya:
  hostname: 10.214.1.32
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0000620276708887
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: pyrpl
nas: !!omap
- na: !!omap [{output_direct: out2}, {input: adc1}, {infer_open_loop_tf: false}, {
      amplitude: 0.5}, {logscale: true}, {avg: 1}, {rbw: [9]}, {start: 100.0}, {stop: 1000.0},
    {points: 5001}, {curve_name: fine piezo}]
spectrum_analyzers: !!omap
- spectrum_analyzer: !!omap [{input: iq1}, {baseband: true}, {center: 0}, {rbw: 1.0}]
lockboxs: !!omap
- lockbox: !!omap
  - fabryperots: !!omap
    - FabryPerot: !!omap [{wavelength: 1064.0}, {finesse: 10000.0}, {length: 180000.0},
        {eta: 1.0}]
  - transmissions: !!omap
    - transmission: !!omap [{mean: 0.18276581913232803}, {rms: 0.0005308628664487906},
        {min: 0.1728515625}, {max: 0.1876220703125}]
  - reflections: !!omap
    - reflection: !!omap [{mean: 0.1823769435286522}, {rms: 0.00038389662406035016},
        {min: 0.173095703125}, {max: 0.18701171875}]
  - pdhs: !!omap
    - pdh: !!omap []
  - sequences: !!omap
    - sequence: !!omap [{stages: !!omap [{states: {}}, {sof: !!omap [{output_on: {
                    fine_piezo: [false, true, 0], coarse_piezo2: [false, false, 0],
                    coarse_piezo: [true, true, 1.0]}}, {variable_value: -1.0}, {input: hf_reflection},
                {duration: 5.0}]}, {pdh: !!omap [{output_on: {fine_piezo: [false,
                      true, 0], coarse_piezo2: [true, false, 0], coarse_piezo: [false,
                      false, 0]}}, {input: hf_reflection}, {variable_value: -0.8},
                {duration: 1.0}]}, {stage3: !!omap [{output_on: {fine_piezo: [true,
                      false, 0], coarse_piezo2: [false, false, 0], coarse_piezo: [
                      false, false, 0]}}, {input: hf_pdh}, {variable_value: 0.0}]}]}]
  - outputs: !!omap
    - coarse_piezo2: !!omap
      - dc_gain: 50.0
      - sweep_amplitude: 0.5
      - sweep_frequency: 5.0
      - i: 1.0
      - name: coarse_piezo2
      - p: 1.0
      - additional_filter:
        - 9714
        - 9714
        - 9714
        - 0
      - assisted_design: true
      - unity_gain_desired: 1.0
      - analog_filter:
        - 1.0
        - 0.0
        - 0.0
        - 0.0
      - tf_type: filter
    - fine_piezo: !!omap
      - i: 10.0
      - p: 0.1
      - dc_gain: -0.1
      - additional_filter:
        - 0
        - 0
        - 0
        - 0
      - output_channel: out2
      - assisted_design: true
      - unity_gain_desired: 10.0
      - analog_filter:
        - 100.0
        - 0.0
        - 0.0
        - 0.0
      - tf_type: filter
    - coarse_piezo: !!omap
      - is_sweepable: true
      - i: 1.5
      - p: 1.5
      - unity_gain_desired: 1.5
      - additional_filter:
        - 9714
        - 9714
        - 9714
        - 0
      - sweep_frequency: 2.0
      - sweep_offset: 0.3
      - sweep_amplitude: 0.5
      - dc_gain: 50.0
      - tf_type: filter
      - assisted_design: true
      - analog_filter:
        - 1.0
        - 0.0
        - 0.0
        - 0.0
  - default_sweep_output: coarse_piezo
  - interferometers: !!omap
    - interferometer: !!omap []
  - direct_inputs: !!omap
    - direct_input1: !!omap []
    - direct_input2: !!omap []
  - model_name: HighFinesseFP
  - high_finesse_fps: !!omap
    - HighFinesseFP: !!omap [{wavelength: 1064.0}, {finesse: 10000.0}, {length: 0.00018},
        {eta: 1.0}]
  - hf_reflections: !!omap
    - hf_reflection: !!omap [{mean: 0.11401071399450302}, {rms: 0.021122724173480552},
        {min: 0.048095703125}, {max: 0.1307373046875}, {adc: adc1}]
  - hf_transmissions: !!omap
    - hf_transmission: !!omap [{mean: 0.11379092186689377}, {rms: 0.02108872028752543},
        {min: 0.0479736328125}, {max: 0.130615234375}]
  - hf_pdhs: !!omap
    - hf_pdh: !!omap [{mod_amp: 0.01}, {mod_phase: 90.0}, {mod_freq: 50000000.0},
        {mod_output: out1}, {adc: adc1}]
- states: {}
hks: !!omap
- hk: !!omap []
amss: !!omap
- ams: !!omap []
scopes: !!omap
- scope: !!omap [{trigger_source: ch1_negative_edge}, {running_continuous: true},
    {duration: 2.147483648}, {trigger_delay: 0.0}, {input2: pid2}, {rolling_mode: true},
    {input1: pid3}, {average: true}, {threshold_ch1: 0.0999755859375}, {threshold_ch2: 0.0},
    {curve_name: ''}]
- states: {sweep: {input2: adc2, input1: adc1, rolling_mode: false, curve_name: '',
      threshold_ch2: 0.0, trigger_delay: 0.0, average: true, threshold_ch1: 0.0799560546875,
      trigger_source: asg1, running_continuous: true, duration: 0.268435456}, rolling: {
      input2: dac1, input1: adc1, rolling_mode: true, curve_name: '', threshold_ch2: 0.0,
      trigger_delay: 0.0, average: true, threshold_ch1: 0.0, trigger_source: asg2,
      running_continuous: true, duration: 2.147483648}, sweep_zoom: {input2: iq1,
      input1: adc1, rolling_mode: false, curve_name: '', threshold_ch2: 0.0, trigger_delay: 0.0,
      average: true, threshold_ch1: 0.0999755859375, trigger_source: ch1_negative_edge,
      running_continuous: true, duration: 0.000262144}}
samplers: !!omap
- sampler: !!omap []
asgs: !!omap
- asg1: !!omap [{output_direct: off}, {frequency: 164.72768038511276}]
- asg2: !!omap [{waveform: cos}, {amplitude: 1.0}, {offset: 0.0}, {frequency: 10.011717677116394},
    {output_direct: off}]
pwms: !!omap
- pwm1: !!omap []
- pwm2: !!omap []
pids: !!omap
- pid1: !!omap
  - output_direct: off
- pid2: !!omap [{setpoint: 0.0894775390625}, {p: 0.0}, {i: 0.0}, {input: adc1}, {
      output_direct: out1}, {inputfilter: [0, 0, 0, 0]}]
- pid3: !!omap [{p: 0.0}, {i: 0.0}, {input: iq1}, {output_direct: out2}, {setpoint: 0.0003662109375},
    {inputfilter: [0, 0, 0, 0]}]
- pid4: !!omap [{p: 0.0}, {i: 0.0}, {setpoint: 0.080322265625}, {input: adc1}, {output_direct: out1},
    {inputfilter: [9714, 9714, 9714, 0]}]
iirs: !!omap
- iir: !!omap []
iqs: !!omap
- iq1: !!omap [{frequency: 49999999.98835847}, {amplitude: 0.01000213623046875}, {
      phase: 90.0}, {output_direct: out1}]
- iq3: !!omap
  - amplitude: 0.0
  - input: adc1
  - acbandwidth:
    - 0
  - frequency: 100.000761449337
  - bandwidth:
    - 9
  - output_signal: output_direct
  - gain: 0.0
  - phase: 0.0
  - output_direct: out2
- iq2: !!omap
  - acbandwidth:
    - 0
  - bandwidth:
    - 159154943
    - 159154943
    - 159154943
    - 159154943
  - quadrature_factor: 0.0
  - output_signal: quadrature
  - gain: 0.0
  - amplitude: 0.0
  - phase: 0.0
  - output_direct: off
