pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
  window_position:
  - -8
  - -8
  - 1920
  - 1137
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAeAAAAESPwBAAAAAfwAAAAAAAAHgAAABzQA/////AIAAAAD/AAA
    ABUAAAJCAAAAAAD////6/////wEAAAAC+wAAAAYAaQBxAHMAAAAAAP////8AAANlAP////sAAAAi
    AHMAcABlAGMAdAByAHUAbQBfAGEAbgBhAGwAeQB6AGUAcgAAAAAA/////wAAA3IA/////AAAABUA
    AARIAAABnAD////8AQAAAAL8AAAAAAAABCQAAAP6AP////wCAAAAAvwAAAAVAAADKAAAAQQBAAAU
    +gAAAAABAAAAAvsAAAAMAHMAYwBvAHAAZQBzAQAAAAD/////AAADjQD////7AAAABABuAGEBAAAA
    AAAABCQAAAP6AP////sAAAAIAGEAcwBnAHMBAAADQQAAARwAAACUAP////sAAAAIAGkAaQByAHMB
    AAAEKAAAA1gAAAM2AP////sAAAAIAHAAaQBkAHMAAAACxQAAAZcAAAHQAP///wAAB4AAAAAAAAAA
    BAAAAAQAAAAIAAAACPwAAAAA
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
asg1:
  frequency: 0
  waveform: sin
  amplitude: 1.0
  trigger_source: immediately
  output_direct: off
  offset: 0.0
asg2:
  frequency: 0
  waveform: sin
  amplitude: 1.0
  trigger_source: immediately
  output_direct: off
  offset: 0.0
asgs: {}
iqs: {}
pids: {}
scopes: {}
iirs: {}
na:
  start: 1000000.0
  curve_name: na_curve
  rbw:
  - 77712
  output_direct: out1
  stop: 2000000.0
  input: adc1
  acbandwidth:
  - 0
  points: 1001
  amplitude: 0.05648160934448233
  avg: 1
spectrum_analyzer:
  window: flattop
  input: asg1
  span:
  - 122071
  center: 999999.9892897904
  points: 16384
  rbw: 0.0
  avg: 10
hk: {}
ams: {}
scope:
  trigger_source: asg1
  average: true
  trigger_delay: 6.5536e-05
  input2: adc2
  threshold_ch1: 0.0
  threshold_ch2: 0.0
  input1: asg1
sampler: {}
adc1: {}
adc2: {}
iq1:
  output_direct: off
  bandwidth:
  - 0
  - 0
  output_signal: quadrature
  frequency: 3.521563485264778
  quadrature_factor: 0.0
  gain: 0.0
  amplitude: 0.0
  phase: 0.0
pid1:
  output_direct: off
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  setpoint: 0.0029296875
  p: 0.0
  i: 0.0
  d: 0.0
  ival: 0.0
pid2:
  output_direct: off
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  input: adc2
  setpoint: 0.068115234375
  p: 11.73828125
  i: 0.0
  d: 0.0
  ival: 0.0
pid3:
  output_direct: off
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  setpoint: 0.0
  p: 363.62451171875
  i: 0.0
  d: 0.0
  ival: 0.0
pid4:
  output_direct: off
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  input: adc2
  setpoint: 0.0
  p: 0.0
  i: 0.0
  d: 0.0
  ival: 0.0
iir:
  output_direct: off
  inputfilter:
  - 0
  on: true
  shortcut: false
  loops: 5
  gain: 0.13520366096496583
  poles:
  - (-21712.834452710875-15680.153081146935j)
  - (-17.205574757853526-859.1906962724538j)
  zeros:
  - (-171.69144935884202-4180.067467134126j)
  - (-157.1999999999997-682.7003731371103j)
