pyrpl: # General configuration of the software:
  name: test_bugs
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAd8AAAD0PwBAAAAAvwAAAAAAAAHfAAABPgA////+gAAAAACAAAA
    BfsAAAAMAHMAYwBvAHAAZQBzAQAAAAD/////AAAA4gD////7AAAACABwAGkAZABzAAAAAAD/////
    AAAAUAD////7AAAABgBpAHEAcwAAAAAA/////wAAAFAA////+wAAAAgAYQBzAGcAcwEAAAAA////
    /wAAAHoA////+wAAAA4AbABvAGMAawBiAG8AeAEAAAAVAAADxwAAAsIA/////AAABOoAAANDAAAA
    AAD////8AgAAAAL8AAAAFQAAA2EAAAAAAP////oAAAACAgAAAAb7AAAABABuAGEAAAAAAP////8A
    AABQAP////sAAAAiAHMAcABlAGMAdAByAHUAbQBfAGEAbgBhAGwAeQB6AGUAcgAAAAAA/////wAA
    AFAA////+wAAACIAcwBwAGUAYwB0AHIAdQBtACAAYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAA
    AAAAAAD7AAAAFABCAGEAcwBlAE0AbwBkAHUAbABlAQAAAAD/////AAAAAAAAAAD7AAAAIABuAGUA
    dAB3AG8AcgBrAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAAAAAAAD7AAAACgBzAGMAbwBw
    AGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMAAAAAFQAAA8cAAABQAP///wAAB3wAAAAA
    AAAABAAAAAQAAAAIAAAACPwAAAAA
  window_position:
  - 322
  - 247
  - 1916
  - 1017
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas: !!omap
- na: !!omap []
spectrum_analyzers: !!omap
- spectrum_analyzer: !!omap []
lockboxs: !!omap
- lockbox: !!omap
  - fabryperots: !!omap
    - FabryPerot: !!omap [{length: 0.0}, {eta: 1.0}]
  - transmissions: !!omap
    - transmission: !!omap [{mean: -0.01944684237241745}, {rms: 0.0005343958661630615},
        {min: -0.0216064453125}, {max: -0.01708984375}]
  - reflections: !!omap
    - reflection: !!omap [{mean: -0.019317708909511566}, {rms: 0.0005358372504009987},
        {min: -0.021240234375}, {max: -0.017333984375}]
  - pdhs: !!omap
    - pdh: !!omap []
  - sequences: !!omap
    - sequence: !!omap [{stages: !!omap [{stage1: !!omap [{name: stage1}, {input: hf_pdh},
                {variable_value: 0.0}, {output_on: {output1: [true, false, 0]}}, {
                  duration: 0.0}, {function_call: ''}]}, {states: {s2: {variable_value: 0.0,
                  input: hf_pdh, function_call: '', duration: 0.0, output_on: {output1: [
                      true, false, 0]}, name: stage2}, s1: {variable_value: 0.0, input: hf_pdh,
                  function_call: '', duration: 0.0, output_on: {output1: [true, false,
                      0]}, name: stage1}}}, {stage2: !!omap []}]}]
    - states: {}
  - outputs: !!omap
    - output1: !!omap
      - name: output1
      - is_sweepable: true
  - high_finesse_fps: !!omap
    - HighFinesseFP: !!omap [{eta: 1.0}, {wavelength: 1064.0}, {finesse: 1000.0},
        {length: 0.01}]
  - model_name: HighFinesseFP
  - interferometers: !!omap
    - interferometer: !!omap []
  - direct_inputs: !!omap
    - direct_input1: !!omap []
    - direct_input2: !!omap []
  - hf_reflections: !!omap
    - hf_reflection: !!omap [{mean: -0.01942066103219986}, {rms: 0.0005346193603254567},
        {min: -0.021484375}, {max: -0.0174560546875}]
  - hf_transmissions: !!omap
    - hf_transmission: !!omap
      - mean: -0.019390836358070374
      - rms: 0.0005453916909060239
      - min: -0.021728515625
      - max: -0.017333984375
  - hf_pdhs: !!omap
    - hf_pdh: !!omap [{mod_amp: 1.0}, {mod_phase: 0.0}, {mod_freq: 50000000.0}]
- states: {}
hks: !!omap
- hk: !!omap []
amss: !!omap
- ams: !!omap []
scopes: !!omap
- scope: !!omap [{trigger_source: asg1}, {trigger_delay: 0.0}, {input1: adc1}, {input2: asg2},
    {duration: 0.004194304}, {average: true}, {threshold_ch1: 0.0}, {threshold_ch2: 0.0},
    {curve_name: ''}, {running_continuous: true}, {rolling_mode: true}, {ch1_active: true},
    {ch2_active: true}]
- states: {coucou: {trigger_source: immediately, input1: adc1, curve_name: '', input2: adc2,
      running_continuous: false, threshold_ch2: 0.0, average: true, trigger_delay: 0.0,
      duration: 0.000131072, rolling_mode: false, threshold_ch1: 0.0}, sweep: {threshold_ch1: 0.0,
      rolling_mode: false, trigger_delay: 0.0, trigger_source: immediately, duration: 0.000131072,
      input1: adc1, threshold_ch2: 0.0, running_continuous: false, average: true,
      input2: adc2, curve_name: ''}, sweep_zoom: {input1: adc1, running_continuous: false,
      curve_name: '', average: true, threshold_ch2: 0.0, duration: 0.000131072, trigger_source: ch1_positive_edge,
      rolling_mode: false, threshold_ch1: 0.0, trigger_delay: 0.0, input2: asg2}}
samplers: !!omap
- sampler: !!omap []
asgs: !!omap
- asg1: !!omap [{frequency: 99999.94654208422}]
- asg2: !!omap []
pwms: !!omap
- pwm1: !!omap []
- pwm2: !!omap []
pids: !!omap
- pid1: !!omap []
- pid2: !!omap []
- pid3: !!omap []
- pid4: !!omap [{p: 1.0}, {i: 0.0}, {setpoint: 0.0}, {input: asg2}, {output_direct: out1}]
iirs: !!omap
- iir: !!omap []
iqs: !!omap
- iq1: !!omap [{amplitude: 1.0}, {phase: 0.0}, {frequency: 49999999.98835847}]
- iq2: !!omap []
