pyrpl:
  name: test_refactor
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAd8AAAD4vwBAAAAAvwAAAAAAAADqwAAAwkA/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAEgAAASQAAADWAP////sAAAAGAGkAcQBzAQAAATwAAAHpAAABSgD/
    ///7AAAACABhAHMAZwBzAQAAAysAAADJAAAAegD////8AAADsQAAA8sAAANuAP////wCAAAAAvwA
    AAASAAABuwAAAScBAAAU+gAAAAACAAAAB/sAAAAEAG4AYQEAAAAA/////wAAANUA////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAlgD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMBAAAAAP////8A
    AAESAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAHTAAAC
    IQAAAa4A////AAAHfAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -1928
  - 117
  - 1916
  - 1030
redpitaya:
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na:
    input: iq2
    output_direct: 'off'
    start: 3000.0
    stop: 10000000.0
    rbw:
    - 1214
    points: 1001
    amplitude: 0.1
    logscale: true
    avg: 1
    acbandwidth:
    - 1214
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {}
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1:
    input: iq1
    acbandwidth:
    - 1214
    frequency: 2999.9937396496534
    bandwidth:
    - 1214
    output_signal: output_direct
    gain: 0.0
    phase: 0.0
    output_direct: 'off'
    amplitude: 0.0
  iq2:
    input: iq2
    acbandwidth:
    - 1214
    frequency: 6196552.800247446
    bandwidth:
    - 1214
    output_signal: output_direct
    gain: 0.0
    phase: 0.0
    output_direct: 'off'
    amplitude: 0.09999847412109375
  iq3:
    bandwidth:
    - 1214
    input: iq2
    acbandwidth:
    - 0
    frequency: 300000.0142492354
    output_signal: output_direct
    gain: 0.0
    amplitude: 0.0
    phase: 0.0
    output_direct: 'off'
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir:
    input: iq3
    loops: 35
    zeros:
    - (-3000+100000j)
    poles:
    - (-3000+50000j)
    gain: 1.0
    output_direct: 'off'
